SetOptions[$FrontEnd, 
NotebookBrowseDirectory->"~/Projects/priv/mathematica-notebooks",
NotebookPath->{
  FrontEnd`FileName[{$UserBaseDirectory, "Autoload", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "Applications", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$BaseDirectory, "Autoload", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$BaseDirectory, "Applications", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Autoload", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Applications", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "SystemFiles", "FrontEnd", 
    "Palettes"}], 
  FrontEnd`FileName[{$BaseDirectory, "SystemFiles", "FrontEnd", "Palettes"}], 
  
  FrontEnd`FileName[{$InstallationDirectory, "Configuration", "FrontEnd", 
    "Palettes"}], 
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", "Components", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", "FrontEnd", 
    "Palettes"}], 
  FrontEnd`FileName[{$HomeDirectory}], 
  FrontEnd`FileName[{$InstallationDirectory}]},
PalettePath->{
  FrontEnd`FileName[{$UserBaseDirectory, "Autoload", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "Applications", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$BaseDirectory, "Autoload", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$BaseDirectory, "Applications", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Autoload", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Applications", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "SystemFiles", "FrontEnd", 
    "Palettes"}], 
  FrontEnd`FileName[{$BaseDirectory, "SystemFiles", "FrontEnd", "Palettes"}], 
  
  FrontEnd`FileName[{$InstallationDirectory, "Configuration", "FrontEnd", 
    "Palettes"}], 
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", "Components", 
    Blank[], "FrontEnd", "Palettes"}], 
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", "FrontEnd", 
    "Palettes"}]},
AutoOpenPalettes->{},
AutoOpenNotebooks->{},
AutoOpenPaclets->{},
StyleSheetPath->{ParentList, 
  FrontEnd`FileName[{
   "/usr/local/Wolfram/Mathematica/10.3/SystemFiles/Components/MUnit/\
FrontEnd", "StyleSheets"}, "PacletManager" -> True]},
DefaultNotebook->"DefaultTemplate.nb",
DefaultStyleDefinitions->"Default.nb",
DefaultPackageStyleDefinitions->"Package.nb",
HomePage->"paclet:guide/WolframRoot",
ReferenceSystemApplication->"Automatic",
SystemConsoleApplication->"Automatic",
WebNotebooksDirectory->"~~Automatic",
WolframCloudBaseUrl->"https://www.wolframcloud.com/",
PreferencesPath->{
  FrontEnd`FileName[{$UserBaseDirectory, "FrontEnd"}], 
  FrontEnd`FileName[{$BaseDirectory, "FrontEnd"}], 
  FrontEnd`FileName[{$InstallationDirectory, "Configuration", "FrontEnd"}], 
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", "FrontEnd"}]},
ConfigurationPath->{
  FrontEnd`FileName[{$InstallationDirectory, "Configuration", "FrontEnd"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "Autoload", 
    Blank[], "Configuration", "FrontEnd"}], 
  FrontEnd`FileName[{$BaseDirectory, "Autoload", 
    Blank[], "Configuration", "FrontEnd"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Autoload", 
    Blank[], "Configuration", "FrontEnd"}]},
SystemHelpPath->{
  FrontEnd`FileName[{$UserBaseDirectory}], 
  FrontEnd`FileName[{$BaseDirectory}], 
  FrontEnd`FileName[{$InstallationDirectory}]},
AddOnHelpPath->{
  FrontEnd`FileName[{$UserBaseDirectory, "Autoload"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "Applications"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "StandardPackages"}], 
  FrontEnd`FileName[{$BaseDirectory, "Autoload"}], 
  FrontEnd`FileName[{$BaseDirectory, "Applications"}], 
  FrontEnd`FileName[{$BaseDirectory, "StandardPackages"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Autoload"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Applications"}], 
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", "Components"}]},
AutoloadPath->{
  FrontEnd`FileName[{$UserBaseDirectory, "Autoload"}], 
  FrontEnd`FileName[{$BaseDirectory, "Autoload"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Autoload"}]},
SpellingDictionariesPath->{
  FrontEnd`FileName[{$UserBaseDirectory, "Autoload", 
    Blank[], "SpellingDictionaries"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "Applications", 
    Blank[], "SpellingDictionaries"}], 
  FrontEnd`FileName[{$BaseDirectory, "Autoload", 
    Blank[], "SpellingDictionaries"}], 
  FrontEnd`FileName[{$BaseDirectory, "Applications", 
    Blank[], "SpellingDictionaries"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Autoload", 
    Blank[], "SpellingDictionaries"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Applications", 
    Blank[], "SpellingDictionaries"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "SystemFiles", 
    "SpellingDictionaries"}], 
  FrontEnd`FileName[{$BaseDirectory, "SystemFiles", "SpellingDictionaries"}], 
  
  FrontEnd`FileName[{$InstallationDirectory, "Configuration", 
    "SpellingDictionaries"}], 
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", "Components", 
    Blank[], "SpellingDictionaries"}], 
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", 
    "SpellingDictionaries"}]},
CharacterEncodingsPath->{
  FrontEnd`FileName[{$UserBaseDirectory, "Autoload", 
    Blank[], "CharacterEncodings"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "Applications", 
    Blank[], "CharacterEncodings"}], 
  FrontEnd`FileName[{$BaseDirectory, "Autoload", 
    Blank[], "CharacterEncodings"}], 
  FrontEnd`FileName[{$BaseDirectory, "Applications", 
    Blank[], "CharacterEncodings"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Autoload", 
    Blank[], "CharacterEncodings"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Applications", 
    Blank[], "CharacterEncodings"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "SystemFiles", 
    "CharacterEncodings"}], 
  FrontEnd`FileName[{$BaseDirectory, "SystemFiles", "CharacterEncodings"}], 
  FrontEnd`FileName[{$InstallationDirectory, "Configuration", 
    "CharacterEncodings"}], 
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", "Components", 
    Blank[], "CharacterEncodings"}], 
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", 
    "CharacterEncodings"}]},
ConvertersPath->{
  FrontEnd`FileName[{$UserBaseDirectory, "Autoload", 
    Blank[], "Converters"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "Applications", 
    Blank[], "Converters"}], 
  FrontEnd`FileName[{$BaseDirectory, "Autoload", 
    Blank[], "Converters"}], 
  FrontEnd`FileName[{$BaseDirectory, "Applications", 
    Blank[], "Converters"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Autoload", 
    Blank[], "Converters"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Applications", 
    Blank[], "Converters"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "SystemFiles", "Converters"}], 
  FrontEnd`FileName[{$BaseDirectory, "SystemFiles", "Converters"}], 
  FrontEnd`FileName[{$InstallationDirectory, "Configuration", "Converters"}], 
  
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", "Components", 
    Blank[], "Converters"}], 
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", "Converters"}]},
PluginsPath->{
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "JLink"}], 
  FrontEnd`FileName[{$InstallationDirectory, "SystemFiles", "Java"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "Autoload", 
    Blank[], "Java"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "Applications", 
    Blank[], "Java"}], 
  FrontEnd`FileName[{$UserBaseDirectory, "StandardPackages", 
    Blank[], "Java"}], 
  FrontEnd`FileName[{$BaseDirectory, "Autoload", 
    Blank[], "Java"}], 
  FrontEnd`FileName[{$BaseDirectory, "Applications", 
    Blank[], "Java"}], 
  FrontEnd`FileName[{$BaseDirectory, "StandardPackages", 
    Blank[], "Java"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Autoload", 
    Blank[], "Java"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "Applications", 
    Blank[], "Java"}], 
  FrontEnd`FileName[{$InstallationDirectory, "AddOns", "StandardPackages", 
    Blank[], "Java"}]},
AllowDownloads->True,
AllowDocumentationUpdates->True,
AllowDataUpdates->True,
AutomaticWolframCloudLogin->True,
WolframId->None,
"DisplayImagePixels"->"Automatic",
Current2DTool->"Select",
Default2DTool->"Select",
IsPersistent2DTool->False,
Current3DTool->"RotateView",
Default3DTool->"RotateView",
IsPersistent3DTool->False,
MultilaunchWarning->False,
FrontEndEventActions->None,
FrontEndDynamicExpression:>Null,
ScreenRectangle->{{0, 1920}, {0, 1200}},
ScreenInformation->{{
  ScreenArea -> {{0, 1920}, {0, 1200}}, 
   FullScreenArea -> {{0, 1920}, {0, 1200}}, BitDepth -> 24, Resolution -> 
   96}},
FrontEndStackSize->262144,
BoxFormattingRecursionLimit->256,
NotebookEvaluateRecursionLimit->100,
MaxUndoSize->16777216,
CaseSensitiveCommandCompletion->True,
PrivateFrontEndOptions->{"LicensesAgreed"->{"10.3"}},
VersionedPreferences->False,
VersionedOptions->{"AutoOpenNotebooks", "PrivateFrontEndOptionsShowAtStartup"},
VersionsLaunched->{"10.3.1"},
EvaluatorStartup->ToExpression[
  FEPrivate`FrontEndResourceString["GetFEKernelInit"]],
JavaVMStartupParameters->{},
DefaultControlPlacement->Automatic,
PreferencesSettings->{"Page"->"Advanced"},
HelpViewerSettings->{"WindowMargins"->{{16, Automatic}, {16, Automatic}},
"WindowSize"->{1507, 1146}},
PrivateFrontEndOptions->{"DialogSettings"->{
 "Login" -> {"RememberMe" -> True}, 
  "WelcomeScreen" -> {"ShowRecentFilesContextMenu" -> False}, 
  "Preferences" -> {
   "SubTabs" -> {
     "Appearance" -> "Numbers", "SyntaxColoring" -> "Other", "Numbers" -> 
      "Formatting"}}},
"InterfaceSettings"->{
 "PredictiveInterface" -> {"ShowMinimized" -> False, "FirstUse" -> False}},
"WolframAlphaSettings"->{
 "BaseURL" -> "Automatic", "Reinterpret" -> True, "Interactive" -> True, 
  "Language" -> Automatic, "SendMathematicaSessionInfo" -> Automatic, "AppID" -> 
  Automatic, "MathematicaFormsFormatType" -> "MostlyInputForm"}},
TransitionEffect->Automatic,
TransitionDirection->Horizontal,
TransitionDuration->Short,
RasterExploreViewRange->17,
MarkerLineThickness->1.,
MarkerAspectRatio->0.,
StyleEnvironment->Automatic,
ScreenStyleEnvironment->"Working",
PrintingStyleEnvironment->"Printout",
ShowPageBreaks->False,
WindowToolbars->{},
RulerUnits->"Inches",
BlinkingCellInsertionPoint->True,
GhostCellInEmptyNotebook->True,
CellInsertionPointColor->GrayLevel[0.7500114442664225],
CellInsertionPointCell->None,
WindowSize->{Automatic, Automatic},
WindowMargins->Automatic,
WindowElements->{
 "StatusArea", "MemoryMonitor", "MagnificationPopUp", "HorizontalScrollBar", 
  "VerticalScrollBar", "MenuBar"},
WindowPersistentStyles->{
 WindowFrame, WindowMargins, WindowSize, DockedCells, Magnification},
BackgroundAppearance->None,
BackgroundAppearanceOptions->"Fill",
WindowTitle->Automatic,
WindowStatusArea->Automatic,
WindowOpacity->1.,
DockedCells->{},
ScrollingOptions->{"HorizontalScrollRange"->Fit,
"PagewiseDisplay"->False,
"ScrollUndo"->False,
"SpeedParameters"->{2., 0.1, 1., 0.4},
"VerticalScrollRange"->Automatic},
PrivateNotebookOptions->{"FinalWindowPrompt"->False},
FormatType->TextForm,
Magnification->1.,
Background->None,
LocatorPaneBoxOptions->{Alignment->{Automatic, Automatic},
Appearance->Automatic,
AutoAction->False,
Background->Automatic,
BaseStyle->{},
BaselinePosition->Automatic,
ContentPadding->True,
ContinuousAction->True,
DefaultBaseStyle->"LocatorPane",
Enabled->Automatic,
Exclusions->{},
FrameMargins->Automatic,
ImageMargins->Automatic,
ImageSize->Automatic,
LocatorAutoCreate->False,
TouchscreenAutoZoom->False,
UseGraphicsRange->All}
]
