alias   l='ls -lFhv --group-directories-first'
alias  la='l -A'
alias  ll='la --color=auto'
alias lll='la --color=never'
alias tree='tree --dirsfirst'
alias dotnet='~/.dotnet/dotnet'
alias fsi='dotnet ~/.dotnet/sdk/2.2.300/FSharp/fsi.exe'
alias fsc='dotnet ~/.dotnet/sdk/2.2.300/FSharp/fsc.exe'
alias tm='tmux'
#alias startx='printf "Use a specialized startx-...\n"'
alias mans='man $(man -k . | sort | fzf -e | awk "{print \$1}")'
