#! /bin/bash

set -e

sleep 3 # wait for dunst to hopefully restart
sudo dmesg --follow --level=emerg,alert,crit,err --since=now \
| while read line
    do
        notify-send -u critical 'dmesg error' "$line"
    done
