#! /bin/bash

set -e

BG_COLOR='#b2b2a0'

#xsetroot -solid "$BG_COLOR"
hsetroot -solid "$BG_COLOR"   # Because xsetroot is incompatible with compton.

if test -f "$FILE_WALLPAPER_CURR"
then
    bg_image=$(< "$FILE_WALLPAPER_CURR")
    feh --bg-scale "$bg_image"
fi
