#! /bin/bash

set -e

WALL_FILE=~/wallpaper.txt

BG_COLOR='#b2b2a0'
BG_IMAGE=$(< "$WALL_FILE")

#xsetroot -solid "$BG_COLOR"
hsetroot -solid "$BG_COLOR"   # Because xsetroot is incompatible with compton.
feh --bg-scale "$BG_IMAGE"
