#! /bin/bash

set -e

BG_COLOR='#b2b2a0'
BG_IMAGE=$(< "$FILE_WALLPAPER_CURR")

#xsetroot -solid "$BG_COLOR"
hsetroot -solid "$BG_COLOR"   # Because xsetroot is incompatible with compton.
feh --bg-scale "$BG_IMAGE"
