#! /bin/sh

set -e

#-- Keyboard layout
# From setxkbmap man page:
#     > Note that setxkbmap adds options specified in the command line to the
#     > options that were set before (as saved in root window  proper‐ ties).
#     > If you want to replace all previously specified options, use the
#     > -option flag with an empty argument first.
#setxkbmap -layout us,ru,el -variant ',phonetic_winkeys,' -option ''
#setxkbmap -layout us,ru,el -variant ',phonetic_winkeys,' -option grp:ctrls_toggle
setxkbmap -layout us,ru -variant ',phonetic_winkeys' -option ''
setxkbmap -layout us,ru -variant ',phonetic_winkeys' -option grp:ctrls_toggle

#xmodmap -e 'remove lock = Caps_Lock'
#setxkbmap -option ctrl:nocaps

setxkbmap -option caps:ctrl_modifier
