#! /bin/sh

set -e

echo "DISPLAY=$DISPLAY" >&2

#-- Keyboard layout
# From setxkbmap man page:
#     > Note that setxkbmap adds options specified in the command line to the
#     > options that were set before (as saved in root window  proper‐ ties).
#     > If you want to replace all previously specified options, use the
#     > -option flag with an empty argument first.

# English, Russian, Greek
#setxkbmap -layout us,ru,el -variant ',phonetic_winkeys,' -option ''
#setxkbmap -layout us,ru,el -variant ',phonetic_winkeys,' -option grp:ctrls_toggle

# English, Russian
setxkbmap -layout us,ru -variant ',phonetic_winkeys' -option ''
setxkbmap -layout us,ru -variant ',phonetic_winkeys' -option grp:ctrls_toggle

# TODO Why did I have this line? What is/was its unique contribution?
xmodmap -e 'remove lock = Caps_Lock'

# XXX Update 1: without this, caps-lock remap goes away after waking up from sleep.
# XXX Update 2: with this, caps-lock remap still goes away after waking up from sleep.
setxkbmap -option ctrl:nocaps

# The actual remapping:
setxkbmap -option caps:ctrl_modifier
